server:  port: 8888  spring:  application:    name: hr-config-server  cloud:    config:      server:        git:          default-label: main          uri: https://github.com/wcosme/ms-course-configs          username: ${GITHUB_USER}          password: ${GITHUB_PASS}

